log:
  level: info
#  file: "/var/log/mosdns.log"

# API 入口设置
api:
  http: "0.0.0.0:9091"

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 10000
      lazy_cache_ttl: 30

  # 转发至国内DNS，并发查询
  - tag: forward_local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: udp://219.141.140.10:53
#          so_mark: 255
        - addr: udp://219.141.136.10:53
#          so_mark: 255

  # 远程dns
  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: tls://1.1.1.1:853
          enable_pipeline: true
          socks5: "192.168.31.3:1081"
        #          so_mark: 255
        - addr: tls://1.0.0.1:853
          enable_pipeline: true
          socks5: "192.168.31.3:1081"
  #          so_mark: 255

  # 自定义hosts
  - tag: hosts
    type: hosts
    args:
      entries:
        - "domain:www2.327237.xyz 172.67.3.3"

  # 国内域名
  - tag: geosite_cn
    type: domain_set
    args:
      exps:
        - "domain:turn.cloudflare.com"
        - "keyword:apple.com"
        - "keyword:aaplimg.com"
        - "keyword:mzstatic.com"
        - "keyword:mzstatic"
        - "keyword:icloud"
        - "keyword:akamaiedge.net"
        - "keyword:digicert.com"
        - "327237.xyz"
      files:
        - "/root/workspace/tools/mosdns/geosite_cn.txt"

  # 国内 IP
  - tag: geoip_cn
    type: ip_set
    args:
      ips:
        - "0.0.0.0/8"  # adguard返回的广告ip, 但是污染的域名同样可能返回这个ip, 发生问题时自己排查
        - "::"
        - "127.0.0.1/8"
        - "::1/128"
        - "10.0.0.0/8"  # 本地网段, 不需要走代理
        - "100.64.0.0/10"
        - "169.254.0.0/16"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "255.255.255.255/32"
        - "3.132.228.0/24"  # nat map ip
        - "fe80::/10"
        - "fc00::/7"
        - "fec0::/10"
        - "2600:1f16:8c5:101::/64"
      files:
        - "/root/workspace/tools/mosdns/geoip_cn.txt"
        - "/root/workspace/tools/mosdns/ip_near.txt"

  - tag: geoip_cloudflare
    type: ip_set
    args:
      ips:
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "108.162.192.0/18"
        - "131.0.72.0/22"
        - "141.101.64.0/18"
        - "162.158.0.0/15"
        - "172.64.0.0/13"
        - "173.245.48.0/20"
        - "188.114.96.0/20"
        - "190.93.240.0/20"
        - "197.234.240.0/22"
        #        - "198.41.128.0/17"
        - "2400:cb00::/32"
        - "2606:4700::/32"
        - "2803:f800::/32"
        - "2405:b500::/32"
        - "2405:8100::/32"
        - "2a06:98c0::/29"
        - "2c0f:f248::/32"

  # 国外域名
  - tag: geosite_no_cn
    type: domain_set
    args:
      exps:
        - "domain:piao.chat"
      files:
        #        - "/var/mosdns/geosite_geolocation-!cn.txt"
        - "/root/workspace/tools/mosdns/gfw.txt"

  # gfw域名
  - tag: geosite_gfw
    type: domain_set
    args:
      files:
        - "/root/workspace/tools/mosdns/gfw.txt"

  - tag: remote_domains
    type: domain_set
    args:
      exps:
        - "keyword:matrix.org"

  - tag: local_ecs
    type: "ecs_handler"
    args:
      forward: true # 是否转发来自下游的 ecs
      preset: "115.171.91.0" # 发送预设 ecs，填写你代理出口附近的IP地址。
      send: true # 是否发送 ecs
      mask4: 24
      mask6: 48

  - tag: fakedns
    type: sequence
    args:
      - matches: "!qtype 1"
        exec: return
      - matches: "!qtype 28"
        exec: return
      - matches: "!resp_ip $geoip_cloudflare"
        exec: return
      - matches: "resp_ip $geoip_cn"
        exec: return
      - exec: forward udp://192.168.31.1:5153
      - exec: accept
        #        exec: nftset inet,xray,gfwlist,ipv4_addr,24 inet,xray,gfwlist6,ipv6_addr,48

  # fallback的primary服务器,返回非国内ip则drop_resp
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local
      - exec: jump fakedns
      - exec: accept

  - tag: remote_sequence
    type: sequence
    args:
      - exec: $local_ecs
      - exec: $forward_remote
      - exec: jump fakedns
      - exec: accept



  # fallback sequence
  - tag: fallback
    type: fallback
    args:
      primary: local_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: false

  # 主运行序列
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - matches: has_resp
        exec: accept

      - matches: qtype 65
        exec: $forward_local
      - exec: prefer_ipv4

      # 缓存逻辑
      - matches: "!qname www1.327237.xyz"
        exec: $cache
      - matches: has_resp
        exec: accept

      # 国内域名走运营商dns
      - matches: qname $geosite_cn
        exec: $forward_local
      - matches: has_resp
        exec: accept

      # fakedns逻辑
      - matches:
          - qname $geosite_gfw
          - qtype 1
        exec: forward udp://192.168.31.1:5153
      - matches: has_resp
        exec: accept

      - matches:
          - qname $geosite_gfw
          - qtype 28
        exec: forward udp://192.168.31.1:5153
      - matches: has_resp
        exec: accept

      - exec: $fallback


  # 启动监听服务
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :5335

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: :5335