log:
  level: info
  file: "/var/log/mosdns.log"

# API 入口设置
api:
  http: "0.0.0.0:9091"

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 10000
      lazy_cache_ttl: 30

  # 转发至国内DNS，并发查询
  - tag: forward_local
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: udp://219.141.140.10:53
          enable_pipeline: true
          enable_http3: false
          so_mark: 255
        - addr: udp://219.141.136.10:53
          enable_pipeline: true
          enable_http3: false
          so_mark: 255

  # 转发至国外DNS，并发查询
  - tag: forward_remote1
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: tls://2606:4700:4700::1111
          enable_pipeline: true
          enable_http3: false
        - addr: tls://2606:4700:4700::1001
          enable_pipeline: true
          enable_http3: false

  # 远程dns2
  - tag: forward_remote2
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: tls://1.1.1.1
          enable_pipeline: true
        - addr: tls://1.0.0.1
          enable_pipeline: true

  # 自定义hosts
  - tag: hosts
    type: hosts
    args:
      entries:
        - "domain:www2.327237.xyz 172.67.3.3"

  # 国内域名
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"
        - "/root/passwall/direct.txt"

  # 国内 IP
  - tag: geoip_cn
    type: ip_set
    args:
      ips:
        - "0.0.0.0/8"  # adguard返回的广告ip, 但是污染的域名同样可能返回这个ip, 发生问题时自己排查
        - "::"
        - "127.0.0.1/8"
        - "::1/128"
        - "10.0.0.0/8"  # 本地网段, 不需要走代理
        - "100.64.0.0/10"
        - "169.254.0.0/16"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
        - "255.255.255.255/32"
        - "3.132.228.0/24"  # nat map ip
        - "fe80::/10"
        - "fc00::/7"
        - "fec0::/10"
        - "2600:1f16:8c5:101::/64"
      files:
        - "/var/mosdns/geoip_cn.txt"

  # 国外域名
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        #        - "/var/mosdns/geosite_geolocation-!cn.txt"
        - "/root/passwall/gfw.txt"

  # gfw域名
  - tag: geosite_gfw
    type: domain_set
    args:
      files:
        - "/root/passwall/gfw.txt"

  - tag: remote_domains
    type: domain_set
    args:
      files:
        - "/root/passwall/remote_domains.txt"

  # fallback的primary服务器,返回非国内ip则drop_resp
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip $geoip_cn"
        exec: nftset inet,xray,gfwlist,ipv4_addr,24 inet,xray,gfwlist6,ipv6_addr,48
      - exec: accept

  # 远程dns1
  - tag: adguard_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: "qname $geosite_cn"
        exec: accept
      - matches: "!resp_ip $geoip_cn"
        exec: nftset inet,xray,gfwlist,ipv4_addr,24 inet,xray,gfwlist6,ipv6_addr,48
      - exec: query_summary local
      - exec: accept

  # fallback的secondary服务器,返回非国内ip则添加至ipset,返回国内ip只接受不会添加ipset
  - tag: remote_sequence1
    type: sequence
    args:
      - exec: $forward_remote1
      - matches: "!resp_ip $geoip_cn"
        exec: nftset inet,xray,gfwlist,ipv4_addr,24 inet,xray,gfwlist6,ipv6_addr,48
      - exec: accept

  - tag: remote_sequence2
    type: sequence
    args:
      - exec: $forward_remote2
      - matches: "!resp_ip $geoip_cn"
        exec: nftset inet,xray,gfwlist,ipv4_addr,24 inet,xray,gfwlist6,ipv6_addr,48
      - exec: accept

  # fallback sequence
  - tag: fallback
    type: fallback
    args:
      primary: local_sequence
      secondary: remote_sequence2
      threshold: 500
      always_standby: true

  # gfwlist解析出的ip添加至ipset，添加前先判断是否为国内ip或内网ip
  - tag: gfw-list
    type: sequence
    args:
      - exec: ttl 600
      - matches: "!resp_ip $geoip_cn"
        exec: nftset inet,xray,gfwlist,ipv4_addr,24 inet,xray,gfwlist6,ipv6_addr,48
      - exec: accept

  - tag: final1
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip $geoip_cn"
        exec: nftset inet,xray,gfwlist,ipv4_addr,24 inet,xray,gfwlist6,ipv6_addr,48
      - matches:
        exec: accept

  - tag: final2
    type: sequence
    args:
      - exec: $remote_sequence1
      - matches: "!resp_ip $geoip_cn"
        exec: nftset inet,xray,gfwlist,ipv4_addr,24 inet,xray,gfwlist6,ipv6_addr,48
      - matches:
        exec: accept

  # 主运行序列
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - matches: has_resp
        exec: accept

      - matches: qtype 65
        exec: reject 3

      # 缓存逻辑
      - matches: "!qname www1.327237.xyz"
        exec: $cache
      - matches: has_resp
        exec: accept

      # 国内域名走运营商dns
      - matches: qname $geosite_cn
        exec: $forward_local
      - matches: has_resp
        exec: accept

      # 走国外dns
      - matches: qname $remote_domains
        exec: $forward_remote2
      - matches: "!resp_ip $geoip_cn"
        exec: nftset inet,xray,gfwlist,ipv4_addr,24 inet,xray,gfwlist6,ipv6_addr,48
      - matches: has_resp
        exec: accept

      # fakedns逻辑
      - matches: qname $geosite_gfw
        exec: forward udp://127.0.0.1:5153
      - matches: has_resp
        exec: accept

      - exec: $fallback


  # 启动监听服务
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :5335

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: :5335